### PR TITLE
Resect email otp logics

### PR DESCRIPTION
**Pull request by folix-01**
Logics moved here : https://github.com/collective/collective.volto.otp to be reusable

### CODE REVIEW

**Comment by mamico** [comment]
@folix-01 Is it possible to enable/disable this feature? Globally or specifically for each form?

**Comment by folix-01** [comment]
> @folix-01 Is it possible to enable/disable this feature? Globally or specifically for each form?

All this logics already working on master, the main target of this pr is to move the otp validation logics to another package. 

As i remember the otp validation is inevitable if u have email in bcc fields, if we want to change this, it may be target of another pr

**Review by mamico — APPROVED** [review]

**Comment by folix-01** [comment]
@sneridagh Can we merge this before we pass to the [new setup](https://github.com/collective/volto-form-block/pull/109) ?

**Comment by sneridagh** [comment]
@folix-01 as long as @pnicolli and @mamico approve it and merge it, is fine, I will rebase. BTW, I didn't check this PR or what is for.

**Comment by mamico** [comment]
As depicted in the comments above, it appears that there are no real changes, but some code moved outside for future code reuse. It's ok for me.

I consider https://github.com/collective/collective.volto.formsupport/issues/57 important, but the issue was not started here.

**Pull request merged**
