### PR TITLE
XML Sending and custom field mapping

### PR DESCRIPTION
**Pull request by JeffersonBledsoe**
Requires collective/volto-form-block#52

## Todo

- [ ] Unit tests

This PR adds supports for attaching an XML file containing the data submitted in the form to the email. This feature is available in collective.easyform and may be useful to those transitioning to Volto. To further help transition [collective.easyform](https://github.com/collective/collective.easyform) users who may be reliant on specific field IDs when using collective.easyform, the ability to customise the label for sending/ downloading XML and CSV was also added.

The below video demonstrates the custom value mapping when downloading the CSV file. The XML after the video was the contents of the file attached to the email sent when submitting the form.

https://user-images.githubusercontent.com/30210785/203632407-ab1e51d1-3374-4613-b010-d2d823402630.mov

```xml
<?xml version='1.0' encoding='utf-8'?><form><field name="Custom field label">My value</field></form>
```

### CODE REVIEW

**Review by cekk — COMMENTED** [review]
LGTM and it's good to keep easyform functionalities.

Can you please update also the changelog and readme with some infos about this new feature?

**Comment by JeffersonBledsoe** [comment]
@cekk I've updated the changelog and docs. Docs aren't my strong point so would you mind having a look over them before merging? 🙂

**Comment by cekk** [comment]
looks good..can you provide some tests for this new feature (sorry, i forgot to tell you)

**Comment by JeffersonBledsoe** [comment]
@cekk Added test!

**Comment by cekk** [comment]
Cool, thanks!

**Pull request merged**
